### ISSUE TITLE
std::initializer_list

### ISSUE THREAD

**Issue by niya3** [PacktPublishing/Cpp17-STL-Cookbook#4]
Can you say why you didn't used `std::list` instead of `std::initializer_list` in `personal_organiser_priority_queue.cpp` ?

**Comment by tfc** [comment]
Hello niya3,

Yes, you are completely right, we could have used `std::list` instead `std::initializer_list`, too. We could also have used `std::vector`, or other linear data structures (`std::deque`, etc.).

My personal preference is: If i know the content at compile time already, then i do not need a data structure that uses heap memory in order to be able to grow. This is why i chose `initializer_list` over `list`.

This recipe is all about `std::priority_queue` and how it organizes its data. So it is not of particular interest where that data really comes from.

Does this answer your question?

**Comment by niya3** [comment]
Yes, thank you.
